;************************INCLUDE FILE*****************************
;(do not assemble stand-alone. For a stand-alone version of this routine see examples/rwts2)


MOVE.NORTH
	;MOVE SOUTH (DOWN)
	
	LDA #$00
	STA MOVE.CURRENT			;SOUTH
	
	DEX GMAP.Y					;LATITUE -1 POSITION NORTH (UP)

	LDA GMAP			
	STA OP1
	LDA GMAP+$1
	STA OP1+$1
	LDA #OFFSET.UP
	STA OP2
	LDA #$00
	STA OP2+$1
	
	JSR SBC.16					;GMAP(2) - #OFFSET.UP(1)
	
	LDA RESULT
	STA GMAP
	LDA RESULT+$1
	STA GMAP+$1
	
	
	;FUTURE: LOGIC FOR REACHING MAP EDGE...EITHER STOP PLAYER FROM DOING SO, TRIGGER AN EVENT OR IMPLEMENT 
	;LOGIC FOR A ROUND WORLD.
	
.NOFLIP
		;**OPT** Speed. Instead of calling TILE.LOOKUP.SCREEN, which uses 11 indexed lookups, maybe create a routine to copy the values up/down 1 row in screen.tile.data. This means there is only 1 indexed lookup. 
	JSR TILE.LOOKUP.SCREEN
	JSR SCROLL.COLUMNS

	LDX #$00
	JSR DRAW.ROW.SINGLE
		;JSR DRAW.SCREEN
	JSR FLIP.PAGE
	
	RTS
	
MOVE.SOUTH
	;MOVE SOUTH (DOWN)
	
	LDA #$01
	STA MOVE.CURRENT			;SOUTH
	
	INC GMAP.Y					;LATITUE +1 POSITION SOUTH (DOWN)

	LDA GMAP			
	STA OP1
	LDA GMAP+$1
	STA OP1+$1
	LDA #OFFSET.DOWN
	STA OP2
	LDA #$00
	STA OP2+$1
	
	JSR ADC.16					;GMAP(2) + #OFFSET.DOWN(1)
	
	LDA RESULT
	STA GMAP
	LDA RESULT+$1
	STA GMAP+$1
	
	
	;FUTURE: LOGIC FOR REACHING MAP EDGE...EITHER STOP PLAYER FROM DOING SO, TRIGGER AN EVENT OR IMPLEMENT 
	;LOGIC FOR A ROUND WORLD.
	
.NOFLIP
		
	JSR TILE.LOOKUP.SCREEN
	JSR SCROLL.COLUMNS
	
		
	LDX #$0A
	JSR DRAW.ROW.SINGLE	
	JSR FLIP.PAGE
	
	RTS
	
MOVE.EAST
	;MOVE EAST (RIGHT)
	
	LDA #$02
	STA MOVE.CURRENT				;EAST
	
	INC GMAP.X					;LONGITUTE +1 POSITION EAST (RIGHT)
	INC GMAP
	BNE .NOFLIP
	INC GMAP+$1
	
	;FUTURE: LOGIC FOR REACHING MAP EDGE...EITHER STOP PLAYER FROM DOING SO, TRIGGER AN EVENT OR IMPLEMENT 
	;LOGIC FOR A ROUND WORLD.
	
.NOFLIP

	JSR TILE.LOOKUP.SCREEN
	JSR SCROLL.ROWS
	
	LDX #$11				;SPECIFY 1ST COLUMN FOR DRAW ROUTINE
	JSR DRAW.COLUMN.SINGLE
	
	JSR FLIP.PAGE
	
	RTS
	
MOVE.WEST
	;MOVE WEST (LEFT)
	LDA #$03
	STA MOVE.CURRENT				;WEST
	
	DEC GMAP.X					;LONGITUTE -1 POSITION WEST (LEFT)
	DEC GMAP
	BNE .NOFLIP
	DEC GMAP+$1
	
	;FUTURE: LOGIC FOR REACHING MAP EDGE...EITHER STOP PLAYER FROM DOING SO, TRIGGER AN EVENT OR IMPLEMENT 
	;LOGIC FOR A ROUND WORLD.
	
.NOFLIP
	JSR TILE.LOOKUP.SCREEN	
	JSR SCROLL.ROWS

	LDX #$00				;SPECIFY 1ST COLUMN FOR DRAW ROUTINE
	JSR DRAW.COLUMN.SINGLE
	
	JSR FLIP.PAGE
	
	RTS
	

;=================DEFINE VARIABLES===============

MOVE.CURRENT .BS		$1		;CONTAINS THE DIRECTION OF THE CURRENT MOVE
